name: Release

on:
    push:

jobs:
    release:
        permissions:
            contents: write
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  persist-credentials: false
            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
            - name: Install dependencies (backend)
              run: npm ci
              working-directory: server
            - name: Install dependencies (frontend)
              run: npm ci
              working-directory: client
            - name: Build frontend
              run: npm run build
              working-directory: client
            - run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
